"""E2E tests for form embed secret CRUD."""

import pytest


def _create_form(client, headers):
    """Create a minimal form for testing."""
    r = client.post("/api/forms", headers=headers, json={
        "name": "Embed Secret Test Form",
        "description": "Test form for embed secrets",
    })
    assert r.status_code == 201, r.text
    return r.json()


@pytest.mark.e2e
class TestFormEmbedSecrets:
    @pytest.fixture
    def test_form(self, e2e_client, platform_admin):
        form = _create_form(e2e_client, platform_admin.headers)
        yield form

    def test_create_embed_secret_autogenerated(self, e2e_client, platform_admin, test_form):
        """Creating a secret without providing one should auto-generate it."""
        r = e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Test Secret"},
        )
        assert r.status_code == 201, r.text
        data = r.json()
        assert "raw_secret" in data
        assert len(data["raw_secret"]) > 20
        assert data["name"] == "Test Secret"
        assert data["is_active"] is True

    def test_create_embed_secret_user_provided(self, e2e_client, platform_admin, test_form):
        """Creating a secret with a user-provided value should store and return it."""
        provided = "my-halo-secret-abc123"
        r = e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Halo Prod", "secret": provided},
        )
        assert r.status_code == 201, r.text
        assert r.json()["raw_secret"] == provided

    def test_list_embed_secrets_hides_raw(self, e2e_client, platform_admin, test_form):
        """Listing secrets should NOT return the raw secret value."""
        e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "Listed Secret"},
        )
        r = e2e_client.get(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
        )
        assert r.status_code == 200, r.text
        secrets_list = r.json()
        assert len(secrets_list) >= 1
        for s in secrets_list:
            assert "raw_secret" not in s
            assert "secret_encrypted" not in s

    def test_deactivate_embed_secret(self, e2e_client, platform_admin, test_form):
        """Should be able to deactivate an embed secret."""
        create_r = e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "To Deactivate"},
        )
        secret_id = create_r.json()["id"]
        r = e2e_client.patch(
            f"/api/forms/{test_form['id']}/embed-secrets/{secret_id}",
            headers=platform_admin.headers,
            json={"is_active": False},
        )
        assert r.status_code == 200, r.text
        assert r.json()["is_active"] is False

    def test_delete_embed_secret(self, e2e_client, platform_admin, test_form):
        """Should be able to delete an embed secret."""
        create_r = e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=platform_admin.headers,
            json={"name": "To Delete"},
        )
        secret_id = create_r.json()["id"]
        r = e2e_client.delete(
            f"/api/forms/{test_form['id']}/embed-secrets/{secret_id}",
            headers=platform_admin.headers,
        )
        assert r.status_code == 204, r.text

    def test_non_admin_cannot_manage_secrets(self, e2e_client, org1_user, test_form):
        """Regular org users should NOT be able to manage embed secrets."""
        r = e2e_client.post(
            f"/api/forms/{test_form['id']}/embed-secrets",
            headers=org1_user.headers,
            json={"name": "Unauthorized"},
        )
        assert r.status_code == 403, r.text
