"""
Bifrost contract models organized by domain.
"""

# Base utilities and helpers
from src.models.contracts.base import (
    DataProviderInputMode,
    IntegrationType,
    RetryPolicy,
    generate_entity_id,
)

# Organizations
from src.models.contracts.organizations import (
    CreateOrganizationRequest,
    OrganizationBase,
    OrganizationCreate,
    OrganizationPublic,
    OrganizationUpdate,
    UpdateOrganizationRequest,
)

# Users & Roles
from src.models.contracts.users import (
    AssignFormsToRoleRequest,
    AssignUsersToRoleRequest,
    CreateRoleRequest,
    CreateUserRequest,
    GrantPermissionsRequest,
    PermissionsData,
    RoleBase,
    RoleCreate,
    RoleFormsResponse,
    RolePublic,
    RoleUpdate,
    RoleUsersResponse,
    UpdateRoleRequest,
    UpdateUserRequest,
    UserBase,
    UserCreate,
    UserFormsResponse,
    UserPermission,
    UserPublic,
    UserResponse,
    UserRolesResponse,
    UserUpdate,
)

# Authentication & MFA
from src.models.contracts.auth import (
    AuthStatusResponse,
    DeviceAuthorizeRequest,
    DeviceCodeResponse,
    DeviceTokenErrorResponse,
    DeviceTokenRequest,
    DeviceTokenResponse,
    LoginResponse,
    MFAEnrollVerifyRequest,
    MFAEnrollVerifyResponse,
    MFARequiredResponse,
    MFASetupRequiredResponse,
    MFASetupResponse,
    MFASetupTokenRequest,
    MFAVerifyRequest,
    OAuthLoginRequest,
    OAuthProviderInfo,
    TokenRefresh,
)

# Passkeys/WebAuthn
from src.models.contracts.passkeys import (
    PasskeyAuthOptionsRequest,
    PasskeyAuthOptionsResponse,
    PasskeyAuthVerifyRequest,
    PasskeyDeleteResponse,
    PasskeyListResponse,
    PasskeyPublic,
    PasskeyRegistrationOptionsRequest,
    PasskeyRegistrationOptionsResponse,
    PasskeyRegistrationVerifyRequest,
    PasskeyRegistrationVerifyResponse,
)

# Forms
from src.models.contracts.forms import (
    CreateFormRequest,
    DataProviderInputConfig,
    FormCreate,
    FormExecuteRequest,
    FormFieldValidation,
    FormPublic,
    FormSchema,
    FormStartupResponse,
    FormUpdate,
    UpdateFormRequest,
)

# Agents & Chat
from src.models.contracts.agents import (
    AgentCreate,
    AgentPublic,
    AgentSummary,
    AgentUpdate,
    AssignAgentsToRoleRequest,
    AssignDelegationsToAgentRequest,
    AssignToolsToAgentRequest,
    ChatRequest,
    ChatResponse,
    ChatStreamChunk,
    ConversationCreate,
    ConversationPublic,
    ConversationSummary,
    MessagePublic,
    RoleAgentsResponse,
    ToolCall,
    ToolResult,
)

# Executions & Logs
from src.models.contracts.executions import (
    AIUsagePublicSimple,
    AIUsageTotalsSimple,
    CleanupTriggeredResponse,
    ExecutionBase,
    ExecutionCreate,
    ExecutionLogPublic,
    ExecutionPublic,
    ExecutionUpdate,
    ExecutionsListResponse,
    StuckExecutionsResponse,
    SystemLog,
    SystemLogsListResponse,
    WorkflowExecution,
    WorkflowExecutionRequest,
    WorkflowExecutionResponse,
)

# Configuration & Secrets
from src.models.contracts.config import (
    ConfigBase,
    ConfigCreate,
    ConfigPublic,
    ConfigResponse,
    ConfigUpdate,
    IntegrationConfig,
    SecretBase,
    SecretCreate,
    SecretCreateRequest,
    SecretListResponse,
    SecretPublic,
    SecretResponse,
    SecretUpdate,
    SecretUpdateRequest,
    SetConfigRequest,
    SetIntegrationConfigRequest,
)

# OAuth Connections
from src.models.contracts.oauth import (
    CreateOAuthConnectionRequest,
    OAuthCallbackRequest,
    OAuthCallbackResponse,
    OAuthConnection,
    OAuthConnectionDetail,
    OAuthConnectionSummary,
    OAuthCredentials,
    OAuthCredentialsModel,
    OAuthCredentialsResponse,
    OAuthFlowType,
    OAuthProviderBase,
    OAuthProviderCreate,
    OAuthProviderPublic,
    OAuthProviderUpdate,
    OAuthStatus,
    UpdateOAuthConnectionRequest,
)

# Workflows & Metadata
from src.models.contracts.workflows import (
    DataProviderMetadata,
    FormDiscoveryMetadata,
    MetadataResponse,
    ValidationIssue,
    WorkflowKey,
    WorkflowKeyCreateRequest,
    WorkflowKeyResponse,
    WorkflowMetadata,
    WorkflowParameter,
    WorkflowValidationRequest,
    WorkflowValidationResponse,
)

# Data Providers
from src.models.contracts.data_providers import (
    DataProviderOption,
    DataProviderRequest,
    DataProviderResponse,
)

# Dashboard & Metrics
from src.models.contracts.dashboard import (
    DailyMetricsEntry,
    DailyMetricsResponse,
    DashboardMetricsResponse,
    ROISnapshot,
    ExecutionStats,
    OrganizationMetricsResponse,
    OrganizationMetricsSummary,
    PlatformMetricsResponse,
    RecentFailure,
    ResourceMetricsEntry,
    ResourceMetricsResponse,
    WorkflowMetricsResponse,
    WorkflowMetricsSummary,
)

# Health
from src.models.contracts.health import (
    BasicHealthResponse,
    GeneralHealthResponse,
    HealthCheck,
)

# Editor & Code
from src.models.contracts.editor import (
    FileConflictResponse,
    FileContentRequest,
    FileContentResponse,
    FileMetadata,
    FileType,
    ScriptExecutionRequest,
    ScriptExecutionResponse,
    SearchRequest,
    SearchResponse,
    SearchResult,
    WorkflowIdConflict,
)

# Common models
from src.models.contracts.common import (
    BrandingSettings,
    BrandingUpdateRequest,
    ErrorResponse,
    FileUploadRequest,
    FileUploadResponse,
    InstallPackageRequest,
    InstalledPackage,
    InstalledPackagesResponse,
    PackageInstallResponse,
    PackageUpdate,
    PackageUpdatesResponse,
    UploadedFileMetadata,
)

# Scheduling & Async Execution
from src.models.contracts.scheduling import (
    AsyncExecution,
    AsyncExecutionStatus,
    CronSchedule,
    CronScheduleCreateRequest,
    CronScheduleUpdateRequest,
    CronValidationRequest,
    CronValidationResponse,
    ProcessSchedulesResponse,
    ScheduleMetadata,
)

# GitHub Integration
from src.models.contracts.github import (
    CommitAndPushRequest,
    CommitAndPushResponse,
    CommitHistoryResponse,
    CommitInfo,
    ConflictInfo,
    CreateRepoRequest,
    CreateRepoResponse,
    DetectedRepoInfo,
    DiscardCommitRequest,
    DiscardUnpushedCommitsResponse,
    FetchFromGitHubResponse,
    FileChange,
    FileDiffRequest,
    FileDiffResponse,
    GitFileStatus,
    GitHubBranchInfo,
    GitHubBranchesResponse,
    GitHubConfigEntity,
    GitHubConfigRequest,
    GitHubConfigResponse,
    GitHubRepoInfo,
    GitHubReposResponse,
    GitHubSetupResponse,
    GitHubSyncRequest,
    GitHubSyncResponse,
    GitRefreshStatusResponse,
    PullFromGitHubRequest,
    PullFromGitHubResponse,
    PushToGitHubRequest,
    PushToGitHubResponse,
    ResolveConflictRequest,
    ResolveConflictResponse,
    ValidateTokenRequest,
    WorkspaceAnalysisResponse,
)

# CLI Models
from src.models.contracts.cli import (
    CLIConfigDeleteRequest,
    CLIConfigGetRequest,
    CLIConfigListRequest,
    CLIConfigSetRequest,
    CLIConfigValue,
    CLIFileDeleteRequest,
    CLIFileListRequest,
    CLIFileReadRequest,
    CLIFileWriteRequest,
    CLIRegisteredWorkflow,
    CLISessionContinueRequest,
    CLISessionContinueResponse,
    CLISessionExecutionSummary,
    CLISessionListResponse,
    CLISessionLogRequest,
    CLISessionPendingResponse,
    CLISessionRegisterRequest,
    CLISessionResponse,
    CLISessionResultRequest,
)

# SDK Response Models (for bifrost.* module returns)
from src.models.contracts.sdk import (
    ConfigData,
    IntegrationData,
    OAuthCredentials as SDKOAuthCredentials,
)

# Profile
from src.models.contracts.profile import (
    PasswordChange,
    ProfileResponse,
    ProfileUpdate,
)

# Notifications
from src.models.contracts.notifications import (
    JobDispatchResponse,
    NotificationCategory,
    NotificationCreate,
    NotificationListResponse,
    NotificationPublic,
    NotificationStatus,
    NotificationUpdate,
    UploadLockInfo,
)

# LLM Configuration
from src.models.contracts.llm import (
    LLMConfigRequest,
    LLMConfigResponse,
    LLMModelsResponse,
    LLMTestRequest,
    LLMTestResponse,
)

# Integrations
from src.models.contracts.integrations import (
    ConfigSchemaItem,
    ConfigItemType,
    IntegrationCreate,
    IntegrationUpdate,
    IntegrationResponse,
    IntegrationDetailResponse,
    IntegrationListResponse,
    IntegrationMappingCreate,
    IntegrationMappingUpdate,
    IntegrationMappingResponse,
    IntegrationMappingListResponse,
    OAuthConfigSummary,
    IntegrationSDKResponse,  # For API SDK endpoint responses (no decrypted tokens)
)

# Decorator Properties
from src.models.contracts.decorators import (
    DecoratorInfo,
    DecoratorPropertiesResponse,
    DecoratorType,
    UpdatePropertiesRequest,
    UpdatePropertiesResponse,
)

# Maintenance
from src.models.contracts.maintenance import (
    MaintenanceStatus,
    ReindexProgress,
    ReindexRequest,
    ReindexResponse,
)

# ROI
from src.models.contracts.roi import (
    ROISettingsRequest,
    ROISettingsResponse,
    ROISummaryResponse,
    WorkflowROIEntry,
    ROIByWorkflowResponse,
    OrganizationROIEntry,
    ROIByOrganizationResponse,
    ROITrendEntry,
    ROITrendsResponse,
)

# AI Usage
from src.models.contracts.ai_usage import (
    AIModelPricingBase,
    AIModelPricingCreate,
    AIModelPricingUpdate,
    AIModelPricingPublic,
    AIModelPricingListItem,
    AIModelPricingListResponse,
    AIUsageBase,
    AIUsagePublic,
    AIUsageTotals,
    AIUsageByModel,
    AIUsageSummaryResponse,
    UsageReportSummary,
    UsageTrend,
    WorkflowUsage,
    ConversationUsage,
    OrganizationUsage,
    KnowledgeStorageUsage,
    KnowledgeStorageTrend,
    UsageReportResponse,
)

__all__ = [
    # Re-export everything defined above
    # NOTE: Bare names like User, Organization, Role, Form, Config, ExecutionLog
    # are NOT exported here to avoid conflicts with ORM models.
    # Use *Public, *Response, *Request suffixed versions instead.
    "RetryPolicy",
    "DataProviderInputMode",
    "IntegrationType",
    "generate_entity_id",
    # Organizations - use OrganizationPublic for responses
    "CreateOrganizationRequest",
    "UpdateOrganizationRequest",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationPublic",
    # Users - use UserPublic/UserResponse for responses
    "CreateUserRequest",
    "UpdateUserRequest",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPublic",
    "UserResponse",
    # Roles - use RolePublic for responses
    "CreateRoleRequest",
    "UpdateRoleRequest",
    "RoleBase",
    "RoleCreate",
    "RoleUpdate",
    "RolePublic",
    # User/Role assignments
    "UserPermission",
    "PermissionsData",
    "GrantPermissionsRequest",
    "UserRolesResponse",
    "UserFormsResponse",
    "RoleUsersResponse",
    "RoleFormsResponse",
    "AssignUsersToRoleRequest",
    "AssignFormsToRoleRequest",
    "OAuthProviderInfo",
    "AuthStatusResponse",
    "MFARequiredResponse",
    "MFASetupRequiredResponse",
    "MFAVerifyRequest",
    "LoginResponse",
    "TokenRefresh",
    "MFASetupTokenRequest",
    "MFASetupResponse",
    "MFAEnrollVerifyRequest",
    "MFAEnrollVerifyResponse",
    "OAuthLoginRequest",
    "DeviceCodeResponse",
    "DeviceTokenRequest",
    "DeviceTokenResponse",
    "DeviceTokenErrorResponse",
    "DeviceAuthorizeRequest",
    # Passkeys/WebAuthn
    "PasskeyRegistrationOptionsRequest",
    "PasskeyRegistrationOptionsResponse",
    "PasskeyRegistrationVerifyRequest",
    "PasskeyRegistrationVerifyResponse",
    "PasskeyAuthOptionsRequest",
    "PasskeyAuthOptionsResponse",
    "PasskeyAuthVerifyRequest",
    "PasskeyPublic",
    "PasskeyListResponse",
    "PasskeyDeleteResponse",
    # Forms - use FormPublic for responses
    "FormFieldValidation",
    "DataProviderInputConfig",
    "FormSchema",
    "CreateFormRequest",
    "UpdateFormRequest",
    "FormExecuteRequest",
    "FormStartupResponse",
    "FormCreate",
    "FormUpdate",
    "FormPublic",
    # Agents & Chat - use AgentPublic for responses
    "AgentCreate",
    "AgentUpdate",
    "AgentPublic",
    "AgentSummary",
    "ConversationCreate",
    "ConversationPublic",
    "ConversationSummary",
    "MessagePublic",
    "ChatRequest",
    "ChatResponse",
    "ChatStreamChunk",
    "ToolCall",
    "ToolResult",
    "AssignAgentsToRoleRequest",
    "AssignToolsToAgentRequest",
    "AssignDelegationsToAgentRequest",
    "RoleAgentsResponse",
    # Executions
    "ExecutionBase",
    "ExecutionLogPublic",
    "AIUsagePublicSimple",
    "AIUsageTotalsSimple",
    "WorkflowExecution",
    "WorkflowExecutionRequest",
    "WorkflowExecutionResponse",
    "ExecutionsListResponse",
    "StuckExecutionsResponse",
    "CleanupTriggeredResponse",
    "ExecutionCreate",
    "ExecutionUpdate",
    "ExecutionPublic",
    "SystemLog",
    "SystemLogsListResponse",
    # Config - use ConfigResponse or ConfigPublic for responses
    "SetConfigRequest",
    "ConfigBase",
    "ConfigCreate",
    "ConfigUpdate",
    "ConfigPublic",
    "ConfigResponse",
    "IntegrationConfig",
    "SetIntegrationConfigRequest",
    "SecretListResponse",
    "SecretCreateRequest",
    "SecretUpdateRequest",
    "SecretResponse",
    "SecretBase",
    "SecretCreate",
    "SecretUpdate",
    "SecretPublic",
    "HealthCheck",
    "BasicHealthResponse",
    "GeneralHealthResponse",
    "ExecutionStats",
    "RecentFailure",
    "ROISnapshot",
    "DashboardMetricsResponse",
    "PlatformMetricsResponse",
    "DailyMetricsEntry",
    "DailyMetricsResponse",
    "OrganizationMetricsSummary",
    "OrganizationMetricsResponse",
    "ResourceMetricsEntry",
    "ResourceMetricsResponse",
    "WorkflowMetricsSummary",
    "WorkflowMetricsResponse",
    "OAuthFlowType",
    "OAuthStatus",
    "CreateOAuthConnectionRequest",
    "UpdateOAuthConnectionRequest",
    "OAuthConnectionSummary",
    "OAuthConnectionDetail",
    "OAuthConnection",
    "OAuthCredentials",
    "OAuthCredentialsModel",
    "OAuthCredentialsResponse",
    "OAuthCallbackRequest",
    "OAuthCallbackResponse",
    "OAuthProviderBase",
    "OAuthProviderCreate",
    "OAuthProviderUpdate",
    "OAuthProviderPublic",
    "FileUploadRequest",
    "FileUploadResponse",
    "UploadedFileMetadata",
    "WorkflowKey",
    "WorkflowKeyCreateRequest",
    "WorkflowKeyResponse",
    "AsyncExecution",
    "AsyncExecutionStatus",
    "CronSchedule",
    "CronScheduleCreateRequest",
    "CronScheduleUpdateRequest",
    "CronValidationRequest",
    "CronValidationResponse",
    "ProcessSchedulesResponse",
    "ScheduleMetadata",
    "BrandingSettings",
    "BrandingUpdateRequest",
    "FileType",
    "FileMetadata",
    "FileContentRequest",
    "FileContentResponse",
    "FileConflictResponse",
    "WorkflowIdConflict",
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "ScriptExecutionRequest",
    "ScriptExecutionResponse",
    "InstallPackageRequest",
    "PackageInstallResponse",
    "InstalledPackage",
    "InstalledPackagesResponse",
    "PackageUpdate",
    "PackageUpdatesResponse",
    "GitFileStatus",
    "FileChange",
    "ConflictInfo",
    "ValidateTokenRequest",
    "GitHubConfigRequest",
    "GitHubConfigResponse",
    "GitHubRepoInfo",
    "GitHubReposResponse",
    "GitHubBranchInfo",
    "WorkspaceAnalysisResponse",
    "CreateRepoRequest",
    "CreateRepoResponse",
    "GitHubBranchesResponse",
    "CommitAndPushRequest",
    "CommitAndPushResponse",
    "PullFromGitHubResponse",
    "FileDiffRequest",
    "FileDiffResponse",
    "ResolveConflictRequest",
    "ResolveConflictResponse",
    "FetchFromGitHubResponse",
    "PushToGitHubRequest",
    "PushToGitHubResponse",
    "PullFromGitHubRequest",
    "PullFromGitHubResponse",
    "GitHubSetupResponse",
    "GitHubSyncRequest",
    "GitHubSyncResponse",
    "GitRefreshStatusResponse",
    "DiscardUnpushedCommitsResponse",
    "DiscardCommitRequest",
    "CommitHistoryResponse",
    "CommitInfo",
    "DetectedRepoInfo",
    "GitHubConfigEntity",
    # CLI Models
    "CLIFileReadRequest",
    "CLIFileWriteRequest",
    "CLIFileListRequest",
    "CLIFileDeleteRequest",
    "CLIConfigGetRequest",
    "CLIConfigSetRequest",
    "CLIConfigListRequest",
    "CLIConfigDeleteRequest",
    "CLIConfigValue",
    # CLI Session Models
    "CLIRegisteredWorkflow",
    "CLISessionRegisterRequest",
    "CLISessionResponse",
    "CLISessionListResponse",
    "CLISessionContinueRequest",
    "CLISessionContinueResponse",
    "CLISessionPendingResponse",
    "CLISessionLogRequest",
    "CLISessionResultRequest",
    "CLISessionExecutionSummary",
    "ErrorResponse",
    "WorkflowParameter",
    "WorkflowMetadata",
    "DataProviderMetadata",
    "MetadataResponse",
    "FormDiscoveryMetadata",
    "ValidationIssue",
    "WorkflowValidationRequest",
    "WorkflowValidationResponse",
    "DataProviderRequest",
    "DataProviderOption",
    "DataProviderResponse",
    # Notifications
    "NotificationCategory",
    "NotificationStatus",
    "NotificationCreate",
    "NotificationUpdate",
    "NotificationPublic",
    "NotificationListResponse",
    "JobDispatchResponse",
    "UploadLockInfo",
    # Profile
    "ProfileUpdate",
    "PasswordChange",
    "ProfileResponse",
    # LLM Configuration
    "LLMConfigRequest",
    "LLMConfigResponse",
    "LLMTestRequest",
    "LLMTestResponse",
    "LLMModelsResponse",
    # Integrations
    "ConfigItemType",
    "ConfigSchemaItem",
    "IntegrationCreate",
    "IntegrationUpdate",
    "IntegrationResponse",
    "IntegrationDetailResponse",
    "IntegrationListResponse",
    "IntegrationMappingCreate",
    "IntegrationMappingUpdate",
    "IntegrationMappingResponse",
    "IntegrationMappingListResponse",
    "IntegrationData",
    "IntegrationSDKResponse",
    "OAuthConfigSummary",
    # Decorator Properties
    "DecoratorType",
    "DecoratorInfo",
    "DecoratorPropertiesResponse",
    "UpdatePropertiesRequest",
    "UpdatePropertiesResponse",
    # Maintenance
    "MaintenanceStatus",
    "ReindexRequest",
    "ReindexProgress",
    "ReindexResponse",
    # ROI
    "ROISettingsRequest",
    "ROISettingsResponse",
    "ROISummaryResponse",
    "WorkflowROIEntry",
    "ROIByWorkflowResponse",
    "OrganizationROIEntry",
    "ROIByOrganizationResponse",
    "ROITrendEntry",
    "ROITrendsResponse",
    # AI Usage
    "AIModelPricingBase",
    "AIModelPricingCreate",
    "AIModelPricingUpdate",
    "AIModelPricingPublic",
    "AIModelPricingListItem",
    "AIModelPricingListResponse",
    "AIUsageBase",
    "AIUsagePublic",
    "AIUsageTotals",
    "AIUsageByModel",
    "AIUsageSummaryResponse",
    "UsageReportSummary",
    "UsageTrend",
    "WorkflowUsage",
    "ConversationUsage",
    "OrganizationUsage",
    "KnowledgeStorageUsage",
    "KnowledgeStorageTrend",
    "UsageReportResponse",
    # SDK Response Models
    "ConfigData",
    "IntegrationData",
    "SDKOAuthCredentials",
]
