"""
CLI contract models for Bifrost (sessions, file operations, config, oauth).
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.models.contracts.workflows import WorkflowParameter


# ==================== CLI SESSION MODELS ====================


class CLIRegisteredWorkflow(BaseModel):
    """Workflow registered by CLI."""

    name: str
    description: str
    parameters: list[WorkflowParameter]


class CLISessionRegisterRequest(BaseModel):
    """Request to register/create a CLI session."""

    session_id: str = Field(description="UUID generated by CLI")
    file_path: str = Field(description="Absolute path to workflow file")
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = Field(default=None, description="Pre-selected workflow name")


class CLISessionExecutionSummary(BaseModel):
    """Summary of an execution within a session."""

    id: str
    workflow_name: str
    status: str
    created_at: datetime
    duration_ms: int | None = None


class CLISessionResponse(BaseModel):
    """Response for a CLI session."""

    id: str
    user_id: str
    file_path: str
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = None
    params: dict[str, Any] | None = None
    pending: bool = False
    last_seen: datetime | None = None
    created_at: datetime
    is_connected: bool = Field(description="True if CLI is actively connected (last_seen within 10s)")
    executions: list[CLISessionExecutionSummary] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class CLISessionListResponse(BaseModel):
    """Response for listing CLI sessions."""

    sessions: list[CLISessionResponse]


class CLISessionContinueRequest(BaseModel):
    """Request to continue workflow execution."""

    workflow_name: str
    params: dict[str, Any]


class CLISessionContinueResponse(BaseModel):
    """Response when continuing workflow execution."""

    status: str
    execution_id: str
    workflow: str


class CLISessionPendingResponse(BaseModel):
    """Response for CLI polling (when execution is pending)."""

    execution_id: str
    workflow_name: str
    params: dict[str, Any]


class CLISessionLogRequest(BaseModel):
    """Log entry from CLI."""

    level: str = Field(description="Log level: DEBUG, INFO, WARNING, ERROR")
    message: str = Field(description="Log message")
    timestamp: str | None = Field(default=None, description="ISO timestamp")
    metadata: dict[str, Any] | None = Field(default=None, description="Additional metadata")


class CLISessionResultRequest(BaseModel):
    """Result from CLI execution."""

    status: str = Field(description="Success or Failed")
    result: Any | None = Field(default=None, description="Return value from workflow")
    error_message: str | None = Field(default=None, description="Error message if failed")
    duration_ms: int | None = Field(default=None, description="Execution duration in ms")
    logs: list[CLISessionLogRequest] = Field(
        default_factory=list,
        description="All logs from execution (sent together to avoid race conditions)"
    )


# ==================== CLI FILE OPERATIONS ====================


class CLIFileReadRequest(BaseModel):
    """Request to read a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileWriteRequest(BaseModel):
    """Request to write a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    content: str = Field(..., description="File content (text)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileListRequest(BaseModel):
    """Request to list files in a directory via CLI."""
    directory: str = Field(default="", description="Directory path (relative)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileDeleteRequest(BaseModel):
    """Request to delete a file or directory via CLI."""
    path: str = Field(..., description="Path to file or directory")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


# ==================== CLI CONFIG OPERATIONS ====================


class CLIConfigGetRequest(BaseModel):
    """Request to get a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigSetRequest(BaseModel):
    """Request to set a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")
    is_secret: bool = Field(
        default=False, description="Whether to encrypt the value")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigListRequest(BaseModel):
    """Request to list config values via CLI."""
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigDeleteRequest(BaseModel):
    """Request to delete a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigValue(BaseModel):
    """Config value response from CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    config_type: str = Field(..., description="Type of the config (string, int, bool, json, secret)")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK INTEGRATIONS MODELS ====================


class SDKIntegrationsGetRequest(BaseModel):
    """Request to get integration configuration via SDK."""
    name: str = Field(..., description="Integration name")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsOAuthData(BaseModel):
    """OAuth data nested in integration response."""
    connection_name: str = Field(..., description="OAuth connection/provider name")
    client_id: str = Field(..., description="OAuth client ID")
    client_secret: str | None = Field(None, description="OAuth client secret (decrypted)")
    authorization_url: str | None = Field(None, description="OAuth authorization URL")
    token_url: str | None = Field(None, description="OAuth token URL (with {entity_id} resolved)")
    scopes: list[str] = Field(default_factory=list, description="OAuth scopes")
    access_token: str | None = Field(None, description="Current access token (decrypted)")
    refresh_token: str | None = Field(None, description="Refresh token (decrypted)")
    expires_at: str | None = Field(None, description="Token expiration (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsGetResponse(BaseModel):
    """Integration data response from SDK."""
    integration_id: str = Field(..., description="Integration UUID")
    entity_id: str | None = Field(None, description="Mapped external entity ID (e.g., tenant ID)")
    entity_name: str | None = Field(None, description="Display name for the mapped entity")
    config: dict[str, Any] = Field(
        default_factory=dict,
        description="Merged configuration (schema defaults + org overrides)"
    )
    oauth: SDKIntegrationsOAuthData | None = Field(
        None, description="Full OAuth credentials and configuration")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsListMappingsRequest(BaseModel):
    """Request to list integration mappings via SDK."""
    name: str = Field(..., description="Integration name")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsMappingItem(BaseModel):
    """Single integration mapping in list response."""
    id: str = Field(..., description="Mapping UUID")
    integration_id: str = Field(..., description="Integration UUID")
    organization_id: str = Field(..., description="Organization UUID")
    entity_id: str = Field(..., description="External entity ID")
    entity_name: str | None = Field(None, description="Display name")
    oauth_token_id: str | None = Field(None, description="Per-org OAuth token override ID")
    config: dict[str, Any] | None = Field(None, description="Organization-specific config")
    created_at: str = Field(..., description="Creation timestamp (ISO format)")
    updated_at: str = Field(..., description="Last update timestamp (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsListMappingsResponse(BaseModel):
    """Response for listing integration mappings."""
    items: list[SDKIntegrationsMappingItem] = Field(..., description="List of mappings")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK AI MODELS ====================


class CLIAICompleteRequest(BaseModel):
    """Request for AI completion via CLI."""
    messages: list[dict[str, str]] = Field(..., description="List of messages with role and content")
    max_tokens: int | None = Field(default=None, description="Override max tokens")
    temperature: float | None = Field(default=None, description="Override temperature (0.0-2.0)")
    org_id: str | None = Field(default=None, description="Organization ID for knowledge search")
    model: str | None = Field(default=None, description="Override model (e.g., 'gpt-4o', 'claude-sonnet-4-20250514')")

    model_config = ConfigDict(from_attributes=True)


class CLIAICompleteResponse(BaseModel):
    """Response from AI completion."""
    content: str | None = Field(None, description="Generated text content")
    input_tokens: int | None = Field(None, description="Number of input tokens")
    output_tokens: int | None = Field(None, description="Number of output tokens")
    model: str | None = Field(None, description="Model identifier used")

    model_config = ConfigDict(from_attributes=True)


class CLIAIInfoResponse(BaseModel):
    """Response with AI model information."""
    provider: str = Field(..., description="LLM provider (openai, anthropic)")
    model: str = Field(..., description="Model identifier")
    max_tokens: int = Field(..., description="Default max tokens")
    temperature: float = Field(..., description="Default temperature")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK KNOWLEDGE MODELS ====================


class CLIKnowledgeStoreRequest(BaseModel):
    """Request to store a document in knowledge store."""
    content: str = Field(..., description="Text content to store and embed")
    namespace: str = Field(default="default", description="Namespace for organization")
    key: str | None = Field(default=None, description="Optional key for upserts")
    metadata: dict[str, Any] | None = Field(default=None, description="Optional metadata dict")
    org_id: str | None = Field(default=None, description="Organization scope")
    scope: str | None = Field(default=None, description="'global' for global scope")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeStoreManyRequest(BaseModel):
    """Request to store multiple documents."""
    documents: list[dict[str, Any]] = Field(..., description="List of document dicts with content, key, metadata")
    namespace: str = Field(default="default", description="Namespace for all documents")
    org_id: str | None = Field(default=None, description="Organization scope")
    scope: str | None = Field(default=None, description="'global' for global scope")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeSearchRequest(BaseModel):
    """Request to search knowledge store."""
    query: str = Field(..., description="Search query (will be embedded)")
    namespace: list[str] = Field(default=["default"], description="Namespace(s) to search")
    limit: int = Field(default=5, description="Maximum results")
    min_score: float | None = Field(default=None, description="Minimum similarity score (0-1)")
    metadata_filter: dict[str, Any] | None = Field(default=None, description="Filter by metadata fields")
    org_id: str | None = Field(default=None, description="Organization scope")
    fallback: bool = Field(default=True, description="If True, also search global scope")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeDocumentResponse(BaseModel):
    """Knowledge document in response."""
    id: str = Field(..., description="Document UUID")
    namespace: str = Field(..., description="Namespace")
    content: str = Field(..., description="Text content")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Metadata")
    score: float | None = Field(default=None, description="Similarity score (0-1)")
    organization_id: str | None = Field(default=None, description="Organization scope")
    key: str | None = Field(default=None, description="User-provided key")
    created_at: str | None = Field(default=None, description="Creation timestamp")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeDeleteRequest(BaseModel):
    """Request to delete a document by key."""
    key: str = Field(..., description="Document key")
    namespace: str = Field(default="default", description="Namespace")
    org_id: str | None = Field(default=None, description="Organization scope")
    scope: str | None = Field(default=None, description="'global' for global scope")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeNamespaceInfo(BaseModel):
    """Namespace information with document counts."""
    namespace: str = Field(..., description="Namespace name")
    scopes: dict[str, int] = Field(..., description="Document counts by scope (global, org, total)")

    model_config = ConfigDict(from_attributes=True)
