"""
CLI contract models for Bifrost (sessions, file operations, config, oauth).
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.models.contracts.workflows import WorkflowParameter


# ==================== CLI SESSION MODELS ====================


class CLIRegisteredWorkflow(BaseModel):
    """Workflow registered by CLI."""

    name: str
    description: str
    parameters: list[WorkflowParameter]


class CLISessionRegisterRequest(BaseModel):
    """Request to register/create a CLI session."""

    session_id: str = Field(description="UUID generated by CLI")
    file_path: str = Field(description="Absolute path to workflow file")
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = Field(default=None, description="Pre-selected workflow name")


class CLISessionExecutionSummary(BaseModel):
    """Summary of an execution within a session."""

    id: str
    workflow_name: str
    status: str
    created_at: datetime
    duration_ms: int | None = None


class CLISessionResponse(BaseModel):
    """Response for a CLI session."""

    id: str
    user_id: str
    file_path: str
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = None
    params: dict[str, Any] | None = None
    pending: bool = False
    last_seen: datetime | None = None
    created_at: datetime
    is_connected: bool = Field(description="True if CLI is actively connected (last_seen within 10s)")
    executions: list[CLISessionExecutionSummary] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class CLISessionListResponse(BaseModel):
    """Response for listing CLI sessions."""

    sessions: list[CLISessionResponse]


class CLISessionContinueRequest(BaseModel):
    """Request to continue workflow execution."""

    workflow_name: str
    params: dict[str, Any]


class CLISessionContinueResponse(BaseModel):
    """Response when continuing workflow execution."""

    status: str
    execution_id: str
    workflow: str


class CLISessionPendingResponse(BaseModel):
    """Response for CLI polling (when execution is pending)."""

    execution_id: str
    workflow_name: str
    params: dict[str, Any]


class CLISessionLogRequest(BaseModel):
    """Log entry from CLI."""

    level: str = Field(description="Log level: DEBUG, INFO, WARNING, ERROR")
    message: str = Field(description="Log message")
    timestamp: str | None = Field(default=None, description="ISO timestamp")
    metadata: dict[str, Any] | None = Field(default=None, description="Additional metadata")


class CLISessionResultRequest(BaseModel):
    """Result from CLI execution."""

    status: str = Field(description="Success or Failed")
    result: Any | None = Field(default=None, description="Return value from workflow")
    error_message: str | None = Field(default=None, description="Error message if failed")
    duration_ms: int | None = Field(default=None, description="Execution duration in ms")
    logs: list[CLISessionLogRequest] = Field(
        default_factory=list,
        description="All logs from execution (sent together to avoid race conditions)"
    )


# ==================== CLI FILE OPERATIONS ====================


class CLIFileReadRequest(BaseModel):
    """Request to read a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileWriteRequest(BaseModel):
    """Request to write a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    content: str = Field(..., description="File content (text)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileListRequest(BaseModel):
    """Request to list files in a directory via CLI."""
    directory: str = Field(default="", description="Directory path (relative)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileDeleteRequest(BaseModel):
    """Request to delete a file or directory via CLI."""
    path: str = Field(..., description="Path to file or directory")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


# ==================== CLI CONFIG OPERATIONS ====================


class CLIConfigGetRequest(BaseModel):
    """Request to get a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIConfigSetRequest(BaseModel):
    """Request to set a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    is_secret: bool = Field(
        default=False, description="Whether to encrypt the value")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIConfigListRequest(BaseModel):
    """Request to list config values via CLI."""
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIConfigDeleteRequest(BaseModel):
    """Request to delete a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIConfigValue(BaseModel):
    """Config value response from CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    config_type: str = Field(..., description="Type of the config (string, int, bool, json, secret)")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK INTEGRATIONS MODELS ====================


class SDKIntegrationsGetRequest(BaseModel):
    """Request to get integration configuration via SDK."""
    name: str = Field(..., description="Integration name")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )
    oauth_scope: str | None = Field(
        default=None,
        description="Override OAuth scope for token request (e.g., 'https://outlook.office365.com/.default'). "
        "When provided, triggers fresh token fetch for client_credentials flows."
    )

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsOAuthData(BaseModel):
    """OAuth data nested in integration response."""
    connection_name: str = Field(..., description="OAuth connection/provider name")
    client_id: str = Field(..., description="OAuth client ID")
    client_secret: str | None = Field(None, description="OAuth client secret (decrypted)")
    authorization_url: str | None = Field(None, description="OAuth authorization URL")
    token_url: str | None = Field(None, description="OAuth token URL (with {entity_id} resolved)")
    scopes: list[str] = Field(default_factory=list, description="OAuth scopes")
    access_token: str | None = Field(None, description="Current access token (decrypted)")
    refresh_token: str | None = Field(None, description="Refresh token (decrypted)")
    expires_at: str | None = Field(None, description="Token expiration (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsGetResponse(BaseModel):
    """Integration data response from SDK."""
    integration_id: str = Field(..., description="Integration UUID")
    entity_id: str | None = Field(None, description="Mapped external entity ID (e.g., tenant ID)")
    entity_name: str | None = Field(None, description="Display name for the mapped entity")
    config: dict[str, Any] = Field(
        default_factory=dict,
        description="Merged configuration (schema defaults + org overrides)"
    )
    oauth: SDKIntegrationsOAuthData | None = Field(
        None, description="Full OAuth credentials and configuration")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsListMappingsRequest(BaseModel):
    """Request to list integration mappings via SDK."""
    name: str = Field(..., description="Integration name")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsMappingItem(BaseModel):
    """Single integration mapping in list response."""
    id: str = Field(..., description="Mapping UUID")
    integration_id: str = Field(..., description="Integration UUID")
    organization_id: str = Field(..., description="Organization UUID")
    entity_id: str = Field(..., description="External entity ID")
    entity_name: str | None = Field(None, description="Display name")
    oauth_token_id: str | None = Field(None, description="Per-org OAuth token override ID")
    config: dict[str, Any] | None = Field(None, description="Organization-specific config")
    created_at: str = Field(..., description="Creation timestamp (ISO format)")
    updated_at: str = Field(..., description="Last update timestamp (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsListMappingsResponse(BaseModel):
    """Response for listing integration mappings."""
    items: list[SDKIntegrationsMappingItem] = Field(..., description="List of mappings")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsGetMappingRequest(BaseModel):
    """Request to get a specific mapping via SDK."""
    name: str = Field(..., description="Integration name")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org"
    )
    entity_id: str | None = Field(default=None, description="External entity ID")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsUpsertMappingRequest(BaseModel):
    """Request to create or update a mapping via SDK."""
    name: str = Field(..., description="Integration name")
    scope: str = Field(..., description="Organization ID (required for upsert)")
    entity_id: str = Field(..., description="External entity ID")
    entity_name: str | None = Field(default=None, description="Display name for the entity")
    config: dict[str, Any] | None = Field(default=None, description="Org-specific configuration")

    model_config = ConfigDict(from_attributes=True)


class SDKIntegrationsDeleteMappingRequest(BaseModel):
    """Request to delete a mapping via SDK."""
    name: str = Field(..., description="Integration name")
    scope: str = Field(..., description="Organization ID (required for delete)")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK AI MODELS ====================


class CLIAICompleteRequest(BaseModel):
    """Request for AI completion via CLI."""
    messages: list[dict[str, str]] = Field(..., description="List of messages with role and content")
    max_tokens: int | None = Field(default=None, description="Override max tokens")
    temperature: float | None = Field(default=None, description="Override temperature (0.0-2.0)")
    org_id: str | None = Field(default=None, description="Organization ID for knowledge search")
    model: str | None = Field(default=None, description="Override model (e.g., 'gpt-4o', 'claude-sonnet-4-20250514')")
    execution_id: str | None = Field(default=None, description="Execution ID for AI usage tracking")

    model_config = ConfigDict(from_attributes=True)


class CLIAICompleteResponse(BaseModel):
    """Response from AI completion."""
    content: str | None = Field(None, description="Generated text content")
    input_tokens: int | None = Field(None, description="Number of input tokens")
    output_tokens: int | None = Field(None, description="Number of output tokens")
    model: str | None = Field(None, description="Model identifier used")

    model_config = ConfigDict(from_attributes=True)


class CLIAIInfoResponse(BaseModel):
    """Response with AI model information."""
    provider: str = Field(..., description="LLM provider (openai, anthropic)")
    model: str = Field(..., description="Model identifier")
    max_tokens: int = Field(..., description="Default max tokens")
    temperature: float = Field(..., description="Default temperature")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK KNOWLEDGE MODELS ====================


class CLIKnowledgeStoreRequest(BaseModel):
    """Request to store a document in knowledge store."""
    content: str = Field(..., description="Text content to store and embed")
    namespace: str = Field(default="default", description="Namespace for organization")
    key: str | None = Field(default=None, description="Optional key for upserts")
    metadata: dict[str, Any] | None = Field(default=None, description="Optional metadata dict")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeStoreManyRequest(BaseModel):
    """Request to store multiple documents."""
    documents: list[dict[str, Any]] = Field(..., description="List of document dicts with content, key, metadata")
    namespace: str = Field(default="default", description="Namespace for all documents")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeSearchRequest(BaseModel):
    """Request to search knowledge store."""
    query: str = Field(..., description="Search query (will be embedded)")
    namespace: list[str] = Field(default=["default"], description="Namespace(s) to search")
    limit: int = Field(default=5, description="Maximum results")
    min_score: float | None = Field(default=None, description="Minimum similarity score (0-1)")
    metadata_filter: dict[str, Any] | None = Field(default=None, description="Filter by metadata fields")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )
    fallback: bool = Field(default=True, description="If True, also search global scope")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeDocumentResponse(BaseModel):
    """Knowledge document in response."""
    id: str = Field(..., description="Document UUID")
    namespace: str = Field(..., description="Namespace")
    content: str = Field(..., description="Text content")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Metadata")
    score: float | None = Field(default=None, description="Similarity score (0-1)")
    organization_id: str | None = Field(default=None, description="Organization scope")
    key: str | None = Field(default=None, description="User-provided key")
    created_at: str | None = Field(default=None, description="Creation timestamp")

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeDeleteRequest(BaseModel):
    """Request to delete a document by key."""
    key: str = Field(..., description="Document key")
    namespace: str = Field(default="default", description="Namespace")
    scope: str | None = Field(
        default=None,
        description="Organization scope: None=context default, UUID=specific org, 'global'=global scope"
    )

    model_config = ConfigDict(from_attributes=True)


class CLIKnowledgeNamespaceInfo(BaseModel):
    """Namespace information with document counts."""
    namespace: str = Field(..., description="Namespace name")
    scopes: dict[str, int] = Field(..., description="Document counts by scope (global, org, total)")

    model_config = ConfigDict(from_attributes=True)


# ==================== SDK TABLES MODELS ====================


class SDKTableCreateRequest(BaseModel):
    """SDK request for creating a table."""
    name: str = Field(..., pattern=r"^[a-z][a-z0-9_]*$", description="Table name (lowercase)")
    table_schema: dict[str, Any] | None = Field(default=None, description="Optional schema hints")
    description: str | None = Field(default=None, description="Table description")
    scope: str | None = Field(
        default=None,
        description="Scope: None=context org, 'global'=global, UUID=specific org",
    )
    app: str | None = Field(default=None, description="Application UUID to scope table to an app")

    model_config = ConfigDict(from_attributes=True)


class SDKTableListRequest(BaseModel):
    """SDK request for listing tables."""
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Filter by application UUID")

    model_config = ConfigDict(from_attributes=True)



class SDKTableInfo(BaseModel):
    """Table info response for SDK."""
    id: str = Field(..., description="Table UUID")
    name: str = Field(..., description="Table name")
    organization_id: str | None = Field(None, description="Organization UUID or null for global")
    application_id: str | None = Field(None, description="Application UUID if app-scoped")
    table_schema: dict[str, Any] | None = Field(None, description="Schema hints")
    description: str | None = Field(None, description="Table description")
    created_at: str = Field(..., description="Creation timestamp (ISO format)")
    updated_at: str = Field(..., description="Last update timestamp (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentInsertRequest(BaseModel):
    """SDK request for inserting a document."""
    table: str = Field(..., description="Table name")
    id: str | None = Field(default=None, description="Document ID (user-provided key). If not provided, a UUID will be auto-generated.")
    data: dict[str, Any] = Field(..., description="Document data")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentUpsertRequest(BaseModel):
    """SDK request for upserting (create or replace) a document."""
    table: str = Field(..., description="Table name")
    id: str = Field(..., description="Document ID (required for upsert)")
    data: dict[str, Any] = Field(..., description="Document data")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentGetRequest(BaseModel):
    """SDK request for getting a document."""
    table: str = Field(..., description="Table name")
    doc_id: str = Field(..., description="Document UUID")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentUpdateRequest(BaseModel):
    """SDK request for updating a document."""
    table: str = Field(..., description="Table name")
    doc_id: str = Field(..., description="Document UUID")
    data: dict[str, Any] = Field(..., description="Fields to update (merged with existing)")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentDeleteRequest(BaseModel):
    """SDK request for deleting a document."""
    table: str = Field(..., description="Table name")
    doc_id: str = Field(..., description="Document UUID")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentQueryRequest(BaseModel):
    """SDK request for querying documents with advanced filtering.

    Filter conditions support:
    - Simple equality: {"status": "active"}
    - Comparison operators: {"amount": {"gt": 100, "lte": 1000}}
    - LIKE patterns: {"name": {"like": "%acme%"}} or {"name": {"ilike": "%ACME%"}}
    - IN lists: {"category": {"in": ["a", "b"]}}
    - NULL checks: {"deleted_at": {"is_null": true}}
    """
    table: str = Field(..., description="Table name")
    where: dict[str, Any] | None = Field(default=None, description="Filter conditions with operators")
    order_by: str | None = Field(default=None, description="Field to order by")
    order_dir: Literal["asc", "desc"] = Field(default="asc", description="Sort direction")
    limit: int = Field(default=100, ge=1, le=1000, description="Max documents")
    offset: int = Field(default=0, ge=0, description="Documents to skip")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentCountRequest(BaseModel):
    """SDK request for counting documents."""
    table: str = Field(..., description="Table name")
    where: dict[str, Any] | None = Field(default=None, description="Filter conditions with operators")
    scope: str | None = Field(default=None, description="Organization scope")
    app: str | None = Field(default=None, description="Application UUID")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentData(BaseModel):
    """Document data response for SDK."""
    id: str = Field(..., description="Document ID (user-provided or auto-generated)")
    table_id: str = Field(..., description="Table UUID")
    data: dict[str, Any] = Field(..., description="Document data")
    created_at: str = Field(..., description="Creation timestamp (ISO format)")
    updated_at: str = Field(..., description="Last update timestamp (ISO format)")

    model_config = ConfigDict(from_attributes=True)


class SDKDocumentList(BaseModel):
    """Document list response for SDK."""
    documents: list[SDKDocumentData] = Field(..., description="List of documents")
    total: int = Field(..., description="Total count")
    limit: int = Field(..., description="Limit used")
    offset: int = Field(..., description="Offset used")

    model_config = ConfigDict(from_attributes=True)
