"""
CLI contract models for Bifrost (sessions, file operations, config, oauth).
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.models.contracts.workflows import WorkflowParameter


# ==================== CLI SESSION MODELS ====================


class CLIRegisteredWorkflow(BaseModel):
    """Workflow registered by CLI."""

    name: str
    description: str
    parameters: list[WorkflowParameter]


class CLISessionRegisterRequest(BaseModel):
    """Request to register/create a CLI session."""

    session_id: str = Field(description="UUID generated by CLI")
    file_path: str = Field(description="Absolute path to workflow file")
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = Field(default=None, description="Pre-selected workflow name")


class CLISessionExecutionSummary(BaseModel):
    """Summary of an execution within a session."""

    id: str
    workflow_name: str
    status: str
    created_at: datetime
    duration_ms: int | None = None


class CLISessionResponse(BaseModel):
    """Response for a CLI session."""

    id: str
    user_id: str
    file_path: str
    workflows: list[CLIRegisteredWorkflow]
    selected_workflow: str | None = None
    params: dict[str, Any] | None = None
    pending: bool = False
    last_seen: datetime | None = None
    created_at: datetime
    is_connected: bool = Field(description="True if CLI is actively connected (last_seen within 10s)")
    executions: list[CLISessionExecutionSummary] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class CLISessionListResponse(BaseModel):
    """Response for listing CLI sessions."""

    sessions: list[CLISessionResponse]


class CLISessionContinueRequest(BaseModel):
    """Request to continue workflow execution."""

    workflow_name: str
    params: dict[str, Any]


class CLISessionContinueResponse(BaseModel):
    """Response when continuing workflow execution."""

    status: str
    execution_id: str
    workflow: str


class CLISessionPendingResponse(BaseModel):
    """Response for CLI polling (when execution is pending)."""

    execution_id: str
    workflow_name: str
    params: dict[str, Any]


class CLISessionLogRequest(BaseModel):
    """Log entry from CLI."""

    level: str = Field(description="Log level: DEBUG, INFO, WARNING, ERROR")
    message: str = Field(description="Log message")
    timestamp: str | None = Field(default=None, description="ISO timestamp")
    metadata: dict[str, Any] | None = Field(default=None, description="Additional metadata")


class CLISessionResultRequest(BaseModel):
    """Result from CLI execution."""

    status: str = Field(description="Success or Failed")
    result: Any | None = Field(default=None, description="Return value from workflow")
    error_message: str | None = Field(default=None, description="Error message if failed")
    duration_ms: int | None = Field(default=None, description="Execution duration in ms")
    logs: list[CLISessionLogRequest] = Field(
        default_factory=list,
        description="All logs from execution (sent together to avoid race conditions)"
    )


# ==================== CLI FILE OPERATIONS ====================


class CLIFileReadRequest(BaseModel):
    """Request to read a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileWriteRequest(BaseModel):
    """Request to write a file via CLI."""
    path: str = Field(..., description="Relative path to file")
    content: str = Field(..., description="File content (text)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileListRequest(BaseModel):
    """Request to list files in a directory via CLI."""
    directory: str = Field(default="", description="Directory path (relative)")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


class CLIFileDeleteRequest(BaseModel):
    """Request to delete a file or directory via CLI."""
    path: str = Field(..., description="Path to file or directory")
    location: Literal["temp", "workspace"] = Field(
        default="workspace", description="Storage location")

    model_config = ConfigDict(from_attributes=True)


# ==================== CLI CONFIG OPERATIONS ====================


class CLIConfigGetRequest(BaseModel):
    """Request to get a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigSetRequest(BaseModel):
    """Request to set a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")
    is_secret: bool = Field(
        default=False, description="Whether to encrypt the value")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigListRequest(BaseModel):
    """Request to list config values via CLI."""
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigDeleteRequest(BaseModel):
    """Request to delete a config value via CLI."""
    key: str = Field(..., description="Configuration key")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIConfigValue(BaseModel):
    """Config value response from CLI."""
    key: str = Field(..., description="Configuration key")
    value: Any = Field(..., description="Configuration value")
    config_type: str = Field(..., description="Type of the config (string, int, bool, json, secret)")

    model_config = ConfigDict(from_attributes=True)


# ==================== CLI OAUTH OPERATIONS ====================


class CLIOAuthGetRequest(BaseModel):
    """Request to get OAuth connection data via CLI."""
    provider: str = Field(..., description="OAuth provider/connection name")
    org_id: str | None = Field(
        default=None, description="Organization ID (optional, uses context default)")

    model_config = ConfigDict(from_attributes=True)


class CLIOAuthGetResponse(BaseModel):
    """OAuth connection data response from CLI."""
    connection_name: str = Field(..., description="Connection/provider name")
    client_id: str = Field(..., description="OAuth client ID")
    client_secret: str | None = Field(None, description="OAuth client secret (decrypted)")
    authorization_url: str | None = Field(None, description="OAuth authorization URL")
    token_url: str | None = Field(None, description="OAuth token URL")
    scopes: list[str] = Field(default_factory=list, description="OAuth scopes")
    access_token: str | None = Field(None, description="Current access token (decrypted)")
    refresh_token: str | None = Field(None, description="Refresh token (decrypted)")
    expires_at: str | None = Field(None, description="Token expiration (ISO format)")

    model_config = ConfigDict(from_attributes=True)
