/**
 * Bifrost module stubs — Vite plugin.
 *
 * Generates the small ESM stub files that the static import map in
 * `client/index.html` references at `/__bifrost_modules/<file>.js`.
 * Each stub is one line per export, re-reading from
 * `globalThis.__bifrost_<key>` populated by `initReactShim()`.
 *
 * Why a static map + stubs at all? Production Firefox 150 ships
 * multi-import-map support gated behind `dom.multiple_import_maps.enabled`
 * (default off), which means it enforces the legacy "register an import
 * map" rule strictly: any `<script type="importmap">` registered after a
 * module load has started is rejected. Static maps in the document source
 * are registered before any module loads, so they always work — but
 * blob: URLs can't appear in static HTML, so we need real URLs that
 * serve the same wrapping logic. That's what this plugin produces.
 *
 * Dev mode: middleware serves stubs on every request (always fresh).
 * Prod build: each stub is emitted as a static asset under
 * `dist/__bifrost_modules/`.
 */

import type { Plugin } from "vite";
import { PLATFORM_MODULES, stubUrlFor } from "../lib/platform-modules";

const VALID_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function buildStubBody(globalKey: string, namedExports: string[]): string {
	const lines: string[] = [
		`// Auto-generated by bifrost-module-stubs Vite plugin. Do not edit.`,
		`const m = globalThis.${globalKey};`,
		`if (!m) throw new Error("globalThis.${globalKey} is not populated. Did initReactShim() run?");`,
		`export default m.default !== undefined ? m.default : m;`,
	];
	for (const name of namedExports) {
		lines.push(`export const ${name} = m[${JSON.stringify(name)}];`);
	}
	return lines.join("\n");
}

async function loadExports(specifier: string): Promise<string[]> {
	const mod = await import(specifier);
	return Object.keys(mod)
		.filter((k) => k !== "default" && VALID_IDENT.test(k))
		.sort();
}

export interface StubManifest {
	specifier: string;
	globalKey: string;
	url: string;
	exports: string[];
}

export async function collectPlatformStubs(): Promise<StubManifest[]> {
	const result: StubManifest[] = [];
	for (const { specifier, globalKey } of PLATFORM_MODULES) {
		const namedExports = await loadExports(specifier);
		result.push({
			specifier,
			globalKey,
			url: stubUrlFor(specifier),
			exports: namedExports,
		});
	}
	return result;
}

export function bifrostModuleStubs(): Plugin {
	let stubs: StubManifest[] = [];

	return {
		name: "bifrost-module-stubs",

		async buildStart() {
			stubs = await collectPlatformStubs();
		},

		generateBundle() {
			for (const { url, globalKey, exports } of stubs) {
				const fileName = url.replace(/^\//, "");
				this.emitFile({
					type: "asset",
					fileName,
					source: buildStubBody(globalKey, exports),
				});
			}
		},

		configureServer(server) {
			server.middlewares.use(
				"/__bifrost_modules",
				async (req, res, next) => {
					if (!req.url) return next();
					const fileName = `__bifrost_modules${req.url.split("?")[0]}`;
					if (stubs.length === 0) {
						stubs = await collectPlatformStubs();
					}
					const stub = stubs.find(
						(s) => s.url.replace(/^\//, "") === fileName,
					);
					if (!stub) return next();
					res.setHeader("Content-Type", "application/javascript");
					res.setHeader("Cache-Control", "no-cache");
					res.end(buildStubBody(stub.globalKey, stub.exports));
				},
			);
		},
	};
}
